name: Ok Rocket
favicon: null
layout_spectrum: 0.05653726099990308
typography_spectrum: 0.95792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eb3346'
    - '#ffffff'
    - '#ff0000'
    - '#f16d7b'
    - '#800000'
  brandStrength: 0.8125
  lightness: 0.5092218576464802
  saturation: 0.21636963682249188
  rhythmicContrast: 0
purpose: []
